receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:

exporters:
  file/logs:
    path: /file-exporter/logs.json
  file/traces:
    path: /file-exporter/traces.json
  file/metrics:
    path: /file-exporter/metrics.json
  debug:
    verbosity: normal
    use_internal_logger: false

service:
  extensions: [ ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ file/traces, debug ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ file/metrics, debug ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ file/logs, debug ]
